updated

diff --git a/bin/Connect_to_Kashet_server b/bin/Connect_to_Kashet_server
--- a/bin/Connect_to_Kashet_server
+++ b/bin/Connect_to_Kashet_server
@@ -3,24 +3,25 @@
 vpn_status=`naclient status | wc -l`
 if [[ $vpn_status > 1 ]] ; then
 	naclient logout >/dev/null
-
-	echo -e "\n****** Connecting to VPN *******"
-	/opt/sslvpn-plus/naclient/gui/naclient.sh &>/dev/null
-
-	if [[ $? == 0 || $? == 1 ]]; then
-		echo -e "Connected to VPN successfully\n\n"
-	else
-		echo -e "Failed to Connect to VPN\n\n"
-		exit
-	fi
 fi
+
+echo -e "\n****** Connecting to VPN *******"
+/opt/sslvpn-plus/naclient/gui/naclient.sh &>/dev/null
+
+if [[ $? == 0 || $? == 1 ]]; then
+	echo -e "Connected to VPN successfully\n\n"
+else
+	echo -e "Failed to Connect to VPN\n\n"
+	exit
+fi
+
+
+
 echo -e "\n****** Connecting to Kashat-server *******"
 
-ssh 192.168.62.12
+ssh 192.168.62.12 >/dev/null
 
-if [[ $? == 0 ]]; then
-	echo -e "Connected to Kashat-server successfully\n\n"
-else
+if [[ $? != 0 ]]; then
 	echo -e "Failed to Connect to Kashat-server\n\n"
 	exit
 fi
