y

diff --git a/bin/functional/download-youtube-single-video-with-multithreding b/bin/functional/download-youtube-single-video-with-multithreding
--- a/bin/functional/download-youtube-single-video-with-multithreding
+++ b/bin/functional/download-youtube-single-video-with-multithreding
@@ -12,9 +12,10 @@
 #                                                   supports aria2c,avconv,axel,c url,ffmpeg,httpie,wget
 # --external-downloader-args "-x 16 -s 16 -k 1M"  :  Give these arguments to the external downloader
 
-echo 
-read -p "Enter links file name: " links_file
-youtube-dl --embed-thumbnail \
+
+if [[ -z $1 ]]; then
+	read -p "Enter links file name: " links_file
+	youtube-dl --embed-thumbnail \
 	--download-archive ytdl-archive.txt \
 	--all-subs \
 	--embed-subs \
@@ -24,3 +25,9 @@ youtube-dl --embed-thumbnail \
 	-a $links_file \
 	--external-downloader aria2c \
 	--external-downloader-args "-x 16 -s 16 -k 1M"
+else
+	youtube-dl -f hd --external-downloader aria2c "$1"
+	if [[ $? -ne 0 ]]; then
+		echo -e "\n\nAn error accured, Starting in normal downloading mode......"
+		youtube-dl -f hd "$1"
+fi
