U

diff --git a/ubuntu-18.04-new-os-installations/bash_profile b/ubuntu-18.04-new-os-installations/bash_profile
--- a/ubuntu-18.04-new-os-installations/bash_profile
+++ b/ubuntu-18.04-new-os-installations/bash_profile
@@ -178,8 +178,8 @@ si(){
     file_name="$1"
     
     if [[ -z $file_name ]] ; then
-    	# echo "\nPlease Enter file name, (eg: si my_file_name\n"
-    	# return 1
+        # echo "\nPlease Enter file name, (eg: si my_file_name\n"
+        # return 1
         file_name=$(max $(ls *.png | sed 's/\.png$//g' | sed  '/[^[:digit:].+-]/d'))
         let "file_name++"
         echo -e "\nYou don't provide a file name, so we saving it as <$file_name.png>\n"
@@ -187,8 +187,14 @@ si(){
 
 
     test -f "$file_name"
-    if [[ $? -eq 0 ]]; then
-        echo -e "\nSorry, the file is exists\n\nCurrently saved .pngs are:\n`ls *.png`\nAborting ......\n\n"
+    res_0=$?
+    test -f "$file_name.png"
+    res_1=$?
+    if [[ $res_0 -eq 0 ]] || [[ $res_1 -eq 0 ]]; then
+        echo -e "\nSorry, the file is exists\n"
+        if [[ $(ls *.png | wc -l) -gt 0 ]] ; then
+            echo -e "Currently saved .pngs are:\n-------------------\n`ls *.png`\n\n\nAborting ......\n\n"
+        fi
         return 1
     fi
     xclip -selection clipboard -t image/png -o > "$file_name.png"
